// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

public interface ExcelGenerationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.qsystem.exceljava.ExcelGenerationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * JSON内容（字符串格式）
   * </pre>
   *
   * <code>string json_content = 1;</code>
   * @return The jsonContent.
   */
  java.lang.String getJsonContent();
  /**
   * <pre>
   * JSON内容（字符串格式）
   * </pre>
   *
   * <code>string json_content = 1;</code>
   * @return The bytes for jsonContent.
   */
  com.google.protobuf.ByteString
      getJsonContentBytes();

  /**
   * <pre>
   * 策略名称
   * </pre>
   *
   * <code>string strategy_name = 2;</code>
   * @return The strategyName.
   */
  java.lang.String getStrategyName();
  /**
   * <pre>
   * 策略名称
   * </pre>
   *
   * <code>string strategy_name = 2;</code>
   * @return The bytes for strategyName.
   */
  com.google.protobuf.ByteString
      getStrategyNameBytes();
}
