// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

public final class ExcelServiceProto {
  private ExcelServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ExcelServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qsystem_exceljava_ExcelGenerationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qsystem_exceljava_ExcelGenerationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qsystem_exceljava_ExcelGenerationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qsystem_exceljava_ExcelGenerationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qsystem_exceljava_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qsystem_exceljava_QueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qsystem_exceljava_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qsystem_exceljava_QueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qsystem_exceljava_QueryDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qsystem_exceljava_QueryDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qsystem_exceljava_QueryDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qsystem_exceljava_QueryDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023excel_service.proto\022\025com.qsystem.excel" +
      "java\"E\n\026ExcelGenerationRequest\022\024\n\014json_c" +
      "ontent\030\001 \001(\t\022\025\n\rstrategy_name\030\002 \001(\t\"\213\001\n\027" +
      "ExcelGenerationResponse\022\017\n\007success\030\001 \001(\010" +
      "\022\027\n\017excel_file_path\030\002 \001(\t\022\025\n\rerror_messa" +
      "ge\030\003 \001(\t\022\021\n\tfile_size\030\004 \001(\003\022\034\n\024generatio" +
      "n_timestamp\030\005 \001(\003\",\n\014QueryRequest\022\r\n\005tok" +
      "en\030\001 \001(\t\022\r\n\005words\030\002 \001(\t\".\n\rQueryResponse" +
      "\022\035\n\025underlying_model_json\030\001 \001(\t\".\n\020Query" +
      "DataRequest\022\r\n\005token\030\001 \001(\t\022\013\n\003tag\030\002 \001(\t\"" +
      "\225\001\n\021QueryDataResponse\022O\n\020query_data_tabl" +
      "e\030\001 \003(\01325.com.qsystem.exceljava.QueryDat" +
      "aResponse.QueryDataRow\032/\n\014QueryDataRow\022\021" +
      "\n\ttimestamp\030\001 \001(\005\022\014\n\004data\030\002 \001(\t2\275\002\n\025Exce" +
      "lGeneratorService\022n\n\rGenerateExcel\022-.com" +
      ".qsystem.exceljava.ExcelGenerationReques" +
      "t\032..com.qsystem.exceljava.ExcelGeneratio" +
      "nResponse\022T\n\005Query\022#.com.qsystem.excelja" +
      "va.QueryRequest\032$.com.qsystem.exceljava." +
      "QueryResponse0\001\022^\n\tQueryData\022\'.com.qsyst" +
      "em.exceljava.QueryDataRequest\032(.com.qsys" +
      "tem.exceljava.QueryDataResponseB1\n\032com.q" +
      "system.exceljava.grpcB\021ExcelServiceProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_qsystem_exceljava_ExcelGenerationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_qsystem_exceljava_ExcelGenerationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qsystem_exceljava_ExcelGenerationRequest_descriptor,
        new java.lang.String[] { "JsonContent", "StrategyName", });
    internal_static_com_qsystem_exceljava_ExcelGenerationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_qsystem_exceljava_ExcelGenerationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qsystem_exceljava_ExcelGenerationResponse_descriptor,
        new java.lang.String[] { "Success", "ExcelFilePath", "ErrorMessage", "FileSize", "GenerationTimestamp", });
    internal_static_com_qsystem_exceljava_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_qsystem_exceljava_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qsystem_exceljava_QueryRequest_descriptor,
        new java.lang.String[] { "Token", "Words", });
    internal_static_com_qsystem_exceljava_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_qsystem_exceljava_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qsystem_exceljava_QueryResponse_descriptor,
        new java.lang.String[] { "UnderlyingModelJson", });
    internal_static_com_qsystem_exceljava_QueryDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_qsystem_exceljava_QueryDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qsystem_exceljava_QueryDataRequest_descriptor,
        new java.lang.String[] { "Token", "Tag", });
    internal_static_com_qsystem_exceljava_QueryDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_qsystem_exceljava_QueryDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qsystem_exceljava_QueryDataResponse_descriptor,
        new java.lang.String[] { "QueryDataTable", });
    internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_descriptor =
      internal_static_com_qsystem_exceljava_QueryDataResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_descriptor,
        new java.lang.String[] { "Timestamp", "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
