// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

public interface ExcelGenerationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.qsystem.exceljava.ExcelGenerationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 生成是否成功
   * </pre>
   *
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * 生成的Excel文件在服务器上的完整路径
   * </pre>
   *
   * <code>string excel_file_path = 2;</code>
   * @return The excelFilePath.
   */
  java.lang.String getExcelFilePath();
  /**
   * <pre>
   * 生成的Excel文件在服务器上的完整路径
   * </pre>
   *
   * <code>string excel_file_path = 2;</code>
   * @return The bytes for excelFilePath.
   */
  com.google.protobuf.ByteString
      getExcelFilePathBytes();

  /**
   * <pre>
   * 错误信息（如果失败）
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   * 错误信息（如果失败）
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * 文件大小（字节）
   * </pre>
   *
   * <code>int64 file_size = 4;</code>
   * @return The fileSize.
   */
  long getFileSize();

  /**
   * <pre>
   * 生成时间戳
   * </pre>
   *
   * <code>int64 generation_timestamp = 5;</code>
   * @return The generationTimestamp.
   */
  long getGenerationTimestamp();
}
