// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

/**
 * <pre>
 * Excel生成请求
 * </pre>
 *
 * Protobuf type {@code com.qsystem.exceljava.ExcelGenerationRequest}
 */
public final class ExcelGenerationRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.qsystem.exceljava.ExcelGenerationRequest)
    ExcelGenerationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ExcelGenerationRequest.class.getName());
  }
  // Use ExcelGenerationRequest.newBuilder() to construct.
  private ExcelGenerationRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExcelGenerationRequest() {
    jsonContent_ = "";
    strategyName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qsystem.exceljava.grpc.ExcelGenerationRequest.class, com.qsystem.exceljava.grpc.ExcelGenerationRequest.Builder.class);
  }

  public static final int JSON_CONTENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jsonContent_ = "";
  /**
   * <pre>
   * JSON内容（字符串格式）
   * </pre>
   *
   * <code>string json_content = 1;</code>
   * @return The jsonContent.
   */
  @java.lang.Override
  public java.lang.String getJsonContent() {
    java.lang.Object ref = jsonContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jsonContent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * JSON内容（字符串格式）
   * </pre>
   *
   * <code>string json_content = 1;</code>
   * @return The bytes for jsonContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsonContentBytes() {
    java.lang.Object ref = jsonContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsonContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRATEGY_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object strategyName_ = "";
  /**
   * <pre>
   * 策略名称
   * </pre>
   *
   * <code>string strategy_name = 2;</code>
   * @return The strategyName.
   */
  @java.lang.Override
  public java.lang.String getStrategyName() {
    java.lang.Object ref = strategyName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      strategyName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 策略名称
   * </pre>
   *
   * <code>string strategy_name = 2;</code>
   * @return The bytes for strategyName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStrategyNameBytes() {
    java.lang.Object ref = strategyName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      strategyName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jsonContent_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, jsonContent_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(strategyName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, strategyName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jsonContent_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, jsonContent_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(strategyName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, strategyName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qsystem.exceljava.grpc.ExcelGenerationRequest)) {
      return super.equals(obj);
    }
    com.qsystem.exceljava.grpc.ExcelGenerationRequest other = (com.qsystem.exceljava.grpc.ExcelGenerationRequest) obj;

    if (!getJsonContent()
        .equals(other.getJsonContent())) return false;
    if (!getStrategyName()
        .equals(other.getStrategyName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JSON_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getJsonContent().hashCode();
    hash = (37 * hash) + STRATEGY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getStrategyName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qsystem.exceljava.grpc.ExcelGenerationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Excel生成请求
   * </pre>
   *
   * Protobuf type {@code com.qsystem.exceljava.ExcelGenerationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.qsystem.exceljava.ExcelGenerationRequest)
      com.qsystem.exceljava.grpc.ExcelGenerationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qsystem.exceljava.grpc.ExcelGenerationRequest.class, com.qsystem.exceljava.grpc.ExcelGenerationRequest.Builder.class);
    }

    // Construct using com.qsystem.exceljava.grpc.ExcelGenerationRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      jsonContent_ = "";
      strategyName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationRequest_descriptor;
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.ExcelGenerationRequest getDefaultInstanceForType() {
      return com.qsystem.exceljava.grpc.ExcelGenerationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.ExcelGenerationRequest build() {
      com.qsystem.exceljava.grpc.ExcelGenerationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.ExcelGenerationRequest buildPartial() {
      com.qsystem.exceljava.grpc.ExcelGenerationRequest result = new com.qsystem.exceljava.grpc.ExcelGenerationRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.qsystem.exceljava.grpc.ExcelGenerationRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.jsonContent_ = jsonContent_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.strategyName_ = strategyName_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qsystem.exceljava.grpc.ExcelGenerationRequest) {
        return mergeFrom((com.qsystem.exceljava.grpc.ExcelGenerationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qsystem.exceljava.grpc.ExcelGenerationRequest other) {
      if (other == com.qsystem.exceljava.grpc.ExcelGenerationRequest.getDefaultInstance()) return this;
      if (!other.getJsonContent().isEmpty()) {
        jsonContent_ = other.jsonContent_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getStrategyName().isEmpty()) {
        strategyName_ = other.strategyName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              jsonContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              strategyName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object jsonContent_ = "";
    /**
     * <pre>
     * JSON内容（字符串格式）
     * </pre>
     *
     * <code>string json_content = 1;</code>
     * @return The jsonContent.
     */
    public java.lang.String getJsonContent() {
      java.lang.Object ref = jsonContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * JSON内容（字符串格式）
     * </pre>
     *
     * <code>string json_content = 1;</code>
     * @return The bytes for jsonContent.
     */
    public com.google.protobuf.ByteString
        getJsonContentBytes() {
      java.lang.Object ref = jsonContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * JSON内容（字符串格式）
     * </pre>
     *
     * <code>string json_content = 1;</code>
     * @param value The jsonContent to set.
     * @return This builder for chaining.
     */
    public Builder setJsonContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jsonContent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * JSON内容（字符串格式）
     * </pre>
     *
     * <code>string json_content = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonContent() {
      jsonContent_ = getDefaultInstance().getJsonContent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * JSON内容（字符串格式）
     * </pre>
     *
     * <code>string json_content = 1;</code>
     * @param value The bytes for jsonContent to set.
     * @return This builder for chaining.
     */
    public Builder setJsonContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jsonContent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object strategyName_ = "";
    /**
     * <pre>
     * 策略名称
     * </pre>
     *
     * <code>string strategy_name = 2;</code>
     * @return The strategyName.
     */
    public java.lang.String getStrategyName() {
      java.lang.Object ref = strategyName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strategyName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 策略名称
     * </pre>
     *
     * <code>string strategy_name = 2;</code>
     * @return The bytes for strategyName.
     */
    public com.google.protobuf.ByteString
        getStrategyNameBytes() {
      java.lang.Object ref = strategyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strategyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 策略名称
     * </pre>
     *
     * <code>string strategy_name = 2;</code>
     * @param value The strategyName to set.
     * @return This builder for chaining.
     */
    public Builder setStrategyName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      strategyName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 策略名称
     * </pre>
     *
     * <code>string strategy_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStrategyName() {
      strategyName_ = getDefaultInstance().getStrategyName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 策略名称
     * </pre>
     *
     * <code>string strategy_name = 2;</code>
     * @param value The bytes for strategyName to set.
     * @return This builder for chaining.
     */
    public Builder setStrategyNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      strategyName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.qsystem.exceljava.ExcelGenerationRequest)
  }

  // @@protoc_insertion_point(class_scope:com.qsystem.exceljava.ExcelGenerationRequest)
  private static final com.qsystem.exceljava.grpc.ExcelGenerationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qsystem.exceljava.grpc.ExcelGenerationRequest();
  }

  public static com.qsystem.exceljava.grpc.ExcelGenerationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExcelGenerationRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExcelGenerationRequest>() {
    @java.lang.Override
    public ExcelGenerationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExcelGenerationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExcelGenerationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qsystem.exceljava.grpc.ExcelGenerationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

