// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

/**
 * <pre>
 * Excel生成响应
 * </pre>
 *
 * Protobuf type {@code com.qsystem.exceljava.ExcelGenerationResponse}
 */
public final class ExcelGenerationResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.qsystem.exceljava.ExcelGenerationResponse)
    ExcelGenerationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ExcelGenerationResponse.class.getName());
  }
  // Use ExcelGenerationResponse.newBuilder() to construct.
  private ExcelGenerationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExcelGenerationResponse() {
    excelFilePath_ = "";
    errorMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qsystem.exceljava.grpc.ExcelGenerationResponse.class, com.qsystem.exceljava.grpc.ExcelGenerationResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <pre>
   * 生成是否成功
   * </pre>
   *
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int EXCEL_FILE_PATH_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object excelFilePath_ = "";
  /**
   * <pre>
   * 生成的Excel文件在服务器上的完整路径
   * </pre>
   *
   * <code>string excel_file_path = 2;</code>
   * @return The excelFilePath.
   */
  @java.lang.Override
  public java.lang.String getExcelFilePath() {
    java.lang.Object ref = excelFilePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      excelFilePath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 生成的Excel文件在服务器上的完整路径
   * </pre>
   *
   * <code>string excel_file_path = 2;</code>
   * @return The bytes for excelFilePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExcelFilePathBytes() {
    java.lang.Object ref = excelFilePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      excelFilePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <pre>
   * 错误信息（如果失败）
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 错误信息（如果失败）
   * </pre>
   *
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_SIZE_FIELD_NUMBER = 4;
  private long fileSize_ = 0L;
  /**
   * <pre>
   * 文件大小（字节）
   * </pre>
   *
   * <code>int64 file_size = 4;</code>
   * @return The fileSize.
   */
  @java.lang.Override
  public long getFileSize() {
    return fileSize_;
  }

  public static final int GENERATION_TIMESTAMP_FIELD_NUMBER = 5;
  private long generationTimestamp_ = 0L;
  /**
   * <pre>
   * 生成时间戳
   * </pre>
   *
   * <code>int64 generation_timestamp = 5;</code>
   * @return The generationTimestamp.
   */
  @java.lang.Override
  public long getGenerationTimestamp() {
    return generationTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(excelFilePath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, excelFilePath_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, errorMessage_);
    }
    if (fileSize_ != 0L) {
      output.writeInt64(4, fileSize_);
    }
    if (generationTimestamp_ != 0L) {
      output.writeInt64(5, generationTimestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(excelFilePath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, excelFilePath_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, errorMessage_);
    }
    if (fileSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, fileSize_);
    }
    if (generationTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, generationTimestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qsystem.exceljava.grpc.ExcelGenerationResponse)) {
      return super.equals(obj);
    }
    com.qsystem.exceljava.grpc.ExcelGenerationResponse other = (com.qsystem.exceljava.grpc.ExcelGenerationResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getExcelFilePath()
        .equals(other.getExcelFilePath())) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (getFileSize()
        != other.getFileSize()) return false;
    if (getGenerationTimestamp()
        != other.getGenerationTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + EXCEL_FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getExcelFilePath().hashCode();
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (37 * hash) + FILE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFileSize());
    hash = (37 * hash) + GENERATION_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGenerationTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qsystem.exceljava.grpc.ExcelGenerationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Excel生成响应
   * </pre>
   *
   * Protobuf type {@code com.qsystem.exceljava.ExcelGenerationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.qsystem.exceljava.ExcelGenerationResponse)
      com.qsystem.exceljava.grpc.ExcelGenerationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qsystem.exceljava.grpc.ExcelGenerationResponse.class, com.qsystem.exceljava.grpc.ExcelGenerationResponse.Builder.class);
    }

    // Construct using com.qsystem.exceljava.grpc.ExcelGenerationResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      excelFilePath_ = "";
      errorMessage_ = "";
      fileSize_ = 0L;
      generationTimestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_ExcelGenerationResponse_descriptor;
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.ExcelGenerationResponse getDefaultInstanceForType() {
      return com.qsystem.exceljava.grpc.ExcelGenerationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.ExcelGenerationResponse build() {
      com.qsystem.exceljava.grpc.ExcelGenerationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.ExcelGenerationResponse buildPartial() {
      com.qsystem.exceljava.grpc.ExcelGenerationResponse result = new com.qsystem.exceljava.grpc.ExcelGenerationResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.qsystem.exceljava.grpc.ExcelGenerationResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.excelFilePath_ = excelFilePath_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.fileSize_ = fileSize_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.generationTimestamp_ = generationTimestamp_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qsystem.exceljava.grpc.ExcelGenerationResponse) {
        return mergeFrom((com.qsystem.exceljava.grpc.ExcelGenerationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qsystem.exceljava.grpc.ExcelGenerationResponse other) {
      if (other == com.qsystem.exceljava.grpc.ExcelGenerationResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getExcelFilePath().isEmpty()) {
        excelFilePath_ = other.excelFilePath_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getFileSize() != 0L) {
        setFileSize(other.getFileSize());
      }
      if (other.getGenerationTimestamp() != 0L) {
        setGenerationTimestamp(other.getGenerationTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              excelFilePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              fileSize_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              generationTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <pre>
     * 生成是否成功
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <pre>
     * 生成是否成功
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 生成是否成功
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object excelFilePath_ = "";
    /**
     * <pre>
     * 生成的Excel文件在服务器上的完整路径
     * </pre>
     *
     * <code>string excel_file_path = 2;</code>
     * @return The excelFilePath.
     */
    public java.lang.String getExcelFilePath() {
      java.lang.Object ref = excelFilePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        excelFilePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 生成的Excel文件在服务器上的完整路径
     * </pre>
     *
     * <code>string excel_file_path = 2;</code>
     * @return The bytes for excelFilePath.
     */
    public com.google.protobuf.ByteString
        getExcelFilePathBytes() {
      java.lang.Object ref = excelFilePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        excelFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 生成的Excel文件在服务器上的完整路径
     * </pre>
     *
     * <code>string excel_file_path = 2;</code>
     * @param value The excelFilePath to set.
     * @return This builder for chaining.
     */
    public Builder setExcelFilePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      excelFilePath_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 生成的Excel文件在服务器上的完整路径
     * </pre>
     *
     * <code>string excel_file_path = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExcelFilePath() {
      excelFilePath_ = getDefaultInstance().getExcelFilePath();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 生成的Excel文件在服务器上的完整路径
     * </pre>
     *
     * <code>string excel_file_path = 2;</code>
     * @param value The bytes for excelFilePath to set.
     * @return This builder for chaining.
     */
    public Builder setExcelFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      excelFilePath_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <pre>
     * 错误信息（如果失败）
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 错误信息（如果失败）
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 错误信息（如果失败）
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息（如果失败）
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误信息（如果失败）
     * </pre>
     *
     * <code>string error_message = 3;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long fileSize_ ;
    /**
     * <pre>
     * 文件大小（字节）
     * </pre>
     *
     * <code>int64 file_size = 4;</code>
     * @return The fileSize.
     */
    @java.lang.Override
    public long getFileSize() {
      return fileSize_;
    }
    /**
     * <pre>
     * 文件大小（字节）
     * </pre>
     *
     * <code>int64 file_size = 4;</code>
     * @param value The fileSize to set.
     * @return This builder for chaining.
     */
    public Builder setFileSize(long value) {

      fileSize_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件大小（字节）
     * </pre>
     *
     * <code>int64 file_size = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileSize() {
      bitField0_ = (bitField0_ & ~0x00000008);
      fileSize_ = 0L;
      onChanged();
      return this;
    }

    private long generationTimestamp_ ;
    /**
     * <pre>
     * 生成时间戳
     * </pre>
     *
     * <code>int64 generation_timestamp = 5;</code>
     * @return The generationTimestamp.
     */
    @java.lang.Override
    public long getGenerationTimestamp() {
      return generationTimestamp_;
    }
    /**
     * <pre>
     * 生成时间戳
     * </pre>
     *
     * <code>int64 generation_timestamp = 5;</code>
     * @param value The generationTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setGenerationTimestamp(long value) {

      generationTimestamp_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 生成时间戳
     * </pre>
     *
     * <code>int64 generation_timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenerationTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      generationTimestamp_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.qsystem.exceljava.ExcelGenerationResponse)
  }

  // @@protoc_insertion_point(class_scope:com.qsystem.exceljava.ExcelGenerationResponse)
  private static final com.qsystem.exceljava.grpc.ExcelGenerationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qsystem.exceljava.grpc.ExcelGenerationResponse();
  }

  public static com.qsystem.exceljava.grpc.ExcelGenerationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExcelGenerationResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExcelGenerationResponse>() {
    @java.lang.Override
    public ExcelGenerationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExcelGenerationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExcelGenerationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qsystem.exceljava.grpc.ExcelGenerationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

