// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

public interface QueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.qsystem.exceljava.QueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 底层模型JSON数据
   * </pre>
   *
   * <code>string underlying_model_json = 1;</code>
   * @return The underlyingModelJson.
   */
  java.lang.String getUnderlyingModelJson();
  /**
   * <pre>
   * 底层模型JSON数据
   * </pre>
   *
   * <code>string underlying_model_json = 1;</code>
   * @return The bytes for underlyingModelJson.
   */
  com.google.protobuf.ByteString
      getUnderlyingModelJsonBytes();
}
