// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

/**
 * <pre>
 * 查询数据响应
 * </pre>
 *
 * Protobuf type {@code com.qsystem.exceljava.QueryDataResponse}
 */
public final class QueryDataResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.qsystem.exceljava.QueryDataResponse)
    QueryDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      QueryDataResponse.class.getName());
  }
  // Use QueryDataResponse.newBuilder() to construct.
  private QueryDataResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private QueryDataResponse() {
    queryDataTable_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qsystem.exceljava.grpc.QueryDataResponse.class, com.qsystem.exceljava.grpc.QueryDataResponse.Builder.class);
  }

  public interface QueryDataRowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qsystem.exceljava.QueryDataResponse.QueryDataRow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int32 timestamp = 1;</code>
     * @return The timestamp.
     */
    int getTimestamp();

    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * <pre>
   * 查询数据行
   * </pre>
   *
   * Protobuf type {@code com.qsystem.exceljava.QueryDataResponse.QueryDataRow}
   */
  public static final class QueryDataRow extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.qsystem.exceljava.QueryDataResponse.QueryDataRow)
      QueryDataRowOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        QueryDataRow.class.getName());
    }
    // Use QueryDataRow.newBuilder() to construct.
    private QueryDataRow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private QueryDataRow() {
      data_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.class, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_ = 0;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int32 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object data_ = "";
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 数据
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0) {
        output.writeInt32(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow)) {
        return super.equals(obj);
      }
      com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow other = (com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 查询数据行
     * </pre>
     *
     * Protobuf type {@code com.qsystem.exceljava.QueryDataResponse.QueryDataRow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qsystem.exceljava.QueryDataResponse.QueryDataRow)
        com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.class, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder.class);
      }

      // Construct using com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0;
        data_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_QueryDataRow_descriptor;
      }

      @java.lang.Override
      public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow getDefaultInstanceForType() {
        return com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.getDefaultInstance();
      }

      @java.lang.Override
      public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow build() {
        com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow buildPartial() {
        com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow result = new com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.data_ = data_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow) {
          return mergeFrom((com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow other) {
        if (other == com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                data_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int timestamp_ ;
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int32 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int32 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(int value) {

        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>int32 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>string data = 2;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>string data = 2;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>string data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>string data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = getDefaultInstance().getData();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据
       * </pre>
       *
       * <code>string data = 2;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qsystem.exceljava.QueryDataResponse.QueryDataRow)
    }

    // @@protoc_insertion_point(class_scope:com.qsystem.exceljava.QueryDataResponse.QueryDataRow)
    private static final com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow();
    }

    public static com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryDataRow>
        PARSER = new com.google.protobuf.AbstractParser<QueryDataRow>() {
      @java.lang.Override
      public QueryDataRow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QueryDataRow> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryDataRow> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int QUERY_DATA_TABLE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow> queryDataTable_;
  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow> getQueryDataTableList() {
    return queryDataTable_;
  }
  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder> 
      getQueryDataTableOrBuilderList() {
    return queryDataTable_;
  }
  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  @java.lang.Override
  public int getQueryDataTableCount() {
    return queryDataTable_.size();
  }
  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  @java.lang.Override
  public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow getQueryDataTable(int index) {
    return queryDataTable_.get(index);
  }
  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  @java.lang.Override
  public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder getQueryDataTableOrBuilder(
      int index) {
    return queryDataTable_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < queryDataTable_.size(); i++) {
      output.writeMessage(1, queryDataTable_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < queryDataTable_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, queryDataTable_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qsystem.exceljava.grpc.QueryDataResponse)) {
      return super.equals(obj);
    }
    com.qsystem.exceljava.grpc.QueryDataResponse other = (com.qsystem.exceljava.grpc.QueryDataResponse) obj;

    if (!getQueryDataTableList()
        .equals(other.getQueryDataTableList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getQueryDataTableCount() > 0) {
      hash = (37 * hash) + QUERY_DATA_TABLE_FIELD_NUMBER;
      hash = (53 * hash) + getQueryDataTableList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.qsystem.exceljava.grpc.QueryDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.qsystem.exceljava.grpc.QueryDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qsystem.exceljava.grpc.QueryDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qsystem.exceljava.grpc.QueryDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 查询数据响应
   * </pre>
   *
   * Protobuf type {@code com.qsystem.exceljava.QueryDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.qsystem.exceljava.QueryDataResponse)
      com.qsystem.exceljava.grpc.QueryDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qsystem.exceljava.grpc.QueryDataResponse.class, com.qsystem.exceljava.grpc.QueryDataResponse.Builder.class);
    }

    // Construct using com.qsystem.exceljava.grpc.QueryDataResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (queryDataTableBuilder_ == null) {
        queryDataTable_ = java.util.Collections.emptyList();
      } else {
        queryDataTable_ = null;
        queryDataTableBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryDataResponse_descriptor;
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.QueryDataResponse getDefaultInstanceForType() {
      return com.qsystem.exceljava.grpc.QueryDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.QueryDataResponse build() {
      com.qsystem.exceljava.grpc.QueryDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.QueryDataResponse buildPartial() {
      com.qsystem.exceljava.grpc.QueryDataResponse result = new com.qsystem.exceljava.grpc.QueryDataResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.qsystem.exceljava.grpc.QueryDataResponse result) {
      if (queryDataTableBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          queryDataTable_ = java.util.Collections.unmodifiableList(queryDataTable_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.queryDataTable_ = queryDataTable_;
      } else {
        result.queryDataTable_ = queryDataTableBuilder_.build();
      }
    }

    private void buildPartial0(com.qsystem.exceljava.grpc.QueryDataResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qsystem.exceljava.grpc.QueryDataResponse) {
        return mergeFrom((com.qsystem.exceljava.grpc.QueryDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qsystem.exceljava.grpc.QueryDataResponse other) {
      if (other == com.qsystem.exceljava.grpc.QueryDataResponse.getDefaultInstance()) return this;
      if (queryDataTableBuilder_ == null) {
        if (!other.queryDataTable_.isEmpty()) {
          if (queryDataTable_.isEmpty()) {
            queryDataTable_ = other.queryDataTable_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureQueryDataTableIsMutable();
            queryDataTable_.addAll(other.queryDataTable_);
          }
          onChanged();
        }
      } else {
        if (!other.queryDataTable_.isEmpty()) {
          if (queryDataTableBuilder_.isEmpty()) {
            queryDataTableBuilder_.dispose();
            queryDataTableBuilder_ = null;
            queryDataTable_ = other.queryDataTable_;
            bitField0_ = (bitField0_ & ~0x00000001);
            queryDataTableBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getQueryDataTableFieldBuilder() : null;
          } else {
            queryDataTableBuilder_.addAllMessages(other.queryDataTable_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow m =
                  input.readMessage(
                      com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.parser(),
                      extensionRegistry);
              if (queryDataTableBuilder_ == null) {
                ensureQueryDataTableIsMutable();
                queryDataTable_.add(m);
              } else {
                queryDataTableBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow> queryDataTable_ =
      java.util.Collections.emptyList();
    private void ensureQueryDataTableIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        queryDataTable_ = new java.util.ArrayList<com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow>(queryDataTable_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder> queryDataTableBuilder_;

    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public java.util.List<com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow> getQueryDataTableList() {
      if (queryDataTableBuilder_ == null) {
        return java.util.Collections.unmodifiableList(queryDataTable_);
      } else {
        return queryDataTableBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public int getQueryDataTableCount() {
      if (queryDataTableBuilder_ == null) {
        return queryDataTable_.size();
      } else {
        return queryDataTableBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow getQueryDataTable(int index) {
      if (queryDataTableBuilder_ == null) {
        return queryDataTable_.get(index);
      } else {
        return queryDataTableBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public Builder setQueryDataTable(
        int index, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow value) {
      if (queryDataTableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueryDataTableIsMutable();
        queryDataTable_.set(index, value);
        onChanged();
      } else {
        queryDataTableBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public Builder setQueryDataTable(
        int index, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder builderForValue) {
      if (queryDataTableBuilder_ == null) {
        ensureQueryDataTableIsMutable();
        queryDataTable_.set(index, builderForValue.build());
        onChanged();
      } else {
        queryDataTableBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public Builder addQueryDataTable(com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow value) {
      if (queryDataTableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueryDataTableIsMutable();
        queryDataTable_.add(value);
        onChanged();
      } else {
        queryDataTableBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public Builder addQueryDataTable(
        int index, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow value) {
      if (queryDataTableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueryDataTableIsMutable();
        queryDataTable_.add(index, value);
        onChanged();
      } else {
        queryDataTableBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public Builder addQueryDataTable(
        com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder builderForValue) {
      if (queryDataTableBuilder_ == null) {
        ensureQueryDataTableIsMutable();
        queryDataTable_.add(builderForValue.build());
        onChanged();
      } else {
        queryDataTableBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public Builder addQueryDataTable(
        int index, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder builderForValue) {
      if (queryDataTableBuilder_ == null) {
        ensureQueryDataTableIsMutable();
        queryDataTable_.add(index, builderForValue.build());
        onChanged();
      } else {
        queryDataTableBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public Builder addAllQueryDataTable(
        java.lang.Iterable<? extends com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow> values) {
      if (queryDataTableBuilder_ == null) {
        ensureQueryDataTableIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, queryDataTable_);
        onChanged();
      } else {
        queryDataTableBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public Builder clearQueryDataTable() {
      if (queryDataTableBuilder_ == null) {
        queryDataTable_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        queryDataTableBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public Builder removeQueryDataTable(int index) {
      if (queryDataTableBuilder_ == null) {
        ensureQueryDataTableIsMutable();
        queryDataTable_.remove(index);
        onChanged();
      } else {
        queryDataTableBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder getQueryDataTableBuilder(
        int index) {
      return getQueryDataTableFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder getQueryDataTableOrBuilder(
        int index) {
      if (queryDataTableBuilder_ == null) {
        return queryDataTable_.get(index);  } else {
        return queryDataTableBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public java.util.List<? extends com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder> 
         getQueryDataTableOrBuilderList() {
      if (queryDataTableBuilder_ != null) {
        return queryDataTableBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(queryDataTable_);
      }
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder addQueryDataTableBuilder() {
      return getQueryDataTableFieldBuilder().addBuilder(
          com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.getDefaultInstance());
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder addQueryDataTableBuilder(
        int index) {
      return getQueryDataTableFieldBuilder().addBuilder(
          index, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.getDefaultInstance());
    }
    /**
     * <pre>
     * 查询数据表
     * </pre>
     *
     * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
     */
    public java.util.List<com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder> 
         getQueryDataTableBuilderList() {
      return getQueryDataTableFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder> 
        getQueryDataTableFieldBuilder() {
      if (queryDataTableBuilder_ == null) {
        queryDataTableBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow.Builder, com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder>(
                queryDataTable_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        queryDataTable_ = null;
      }
      return queryDataTableBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.qsystem.exceljava.QueryDataResponse)
  }

  // @@protoc_insertion_point(class_scope:com.qsystem.exceljava.QueryDataResponse)
  private static final com.qsystem.exceljava.grpc.QueryDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qsystem.exceljava.grpc.QueryDataResponse();
  }

  public static com.qsystem.exceljava.grpc.QueryDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<QueryDataResponse>() {
    @java.lang.Override
    public QueryDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QueryDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qsystem.exceljava.grpc.QueryDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

