// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

public interface QueryDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.qsystem.exceljava.QueryDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  java.util.List<com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow> 
      getQueryDataTableList();
  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRow getQueryDataTable(int index);
  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  int getQueryDataTableCount();
  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  java.util.List<? extends com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder> 
      getQueryDataTableOrBuilderList();
  /**
   * <pre>
   * 查询数据表
   * </pre>
   *
   * <code>repeated .com.qsystem.exceljava.QueryDataResponse.QueryDataRow query_data_table = 1;</code>
   */
  com.qsystem.exceljava.grpc.QueryDataResponse.QueryDataRowOrBuilder getQueryDataTableOrBuilder(
      int index);
}
