// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

/**
 * <pre>
 * 查询响应
 * </pre>
 *
 * Protobuf type {@code com.qsystem.exceljava.QueryResponse}
 */
public final class QueryResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.qsystem.exceljava.QueryResponse)
    QueryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      QueryResponse.class.getName());
  }
  // Use QueryResponse.newBuilder() to construct.
  private QueryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private QueryResponse() {
    underlyingModelJson_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qsystem.exceljava.grpc.QueryResponse.class, com.qsystem.exceljava.grpc.QueryResponse.Builder.class);
  }

  public static final int UNDERLYING_MODEL_JSON_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object underlyingModelJson_ = "";
  /**
   * <pre>
   * 底层模型JSON数据
   * </pre>
   *
   * <code>string underlying_model_json = 1;</code>
   * @return The underlyingModelJson.
   */
  @java.lang.Override
  public java.lang.String getUnderlyingModelJson() {
    java.lang.Object ref = underlyingModelJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      underlyingModelJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 底层模型JSON数据
   * </pre>
   *
   * <code>string underlying_model_json = 1;</code>
   * @return The bytes for underlyingModelJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnderlyingModelJsonBytes() {
    java.lang.Object ref = underlyingModelJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      underlyingModelJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(underlyingModelJson_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, underlyingModelJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(underlyingModelJson_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, underlyingModelJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qsystem.exceljava.grpc.QueryResponse)) {
      return super.equals(obj);
    }
    com.qsystem.exceljava.grpc.QueryResponse other = (com.qsystem.exceljava.grpc.QueryResponse) obj;

    if (!getUnderlyingModelJson()
        .equals(other.getUnderlyingModelJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UNDERLYING_MODEL_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getUnderlyingModelJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.qsystem.exceljava.grpc.QueryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.qsystem.exceljava.grpc.QueryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.qsystem.exceljava.grpc.QueryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qsystem.exceljava.grpc.QueryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 查询响应
   * </pre>
   *
   * Protobuf type {@code com.qsystem.exceljava.QueryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.qsystem.exceljava.QueryResponse)
      com.qsystem.exceljava.grpc.QueryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qsystem.exceljava.grpc.QueryResponse.class, com.qsystem.exceljava.grpc.QueryResponse.Builder.class);
    }

    // Construct using com.qsystem.exceljava.grpc.QueryResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      underlyingModelJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qsystem.exceljava.grpc.ExcelServiceProto.internal_static_com_qsystem_exceljava_QueryResponse_descriptor;
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.QueryResponse getDefaultInstanceForType() {
      return com.qsystem.exceljava.grpc.QueryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.QueryResponse build() {
      com.qsystem.exceljava.grpc.QueryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qsystem.exceljava.grpc.QueryResponse buildPartial() {
      com.qsystem.exceljava.grpc.QueryResponse result = new com.qsystem.exceljava.grpc.QueryResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.qsystem.exceljava.grpc.QueryResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.underlyingModelJson_ = underlyingModelJson_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qsystem.exceljava.grpc.QueryResponse) {
        return mergeFrom((com.qsystem.exceljava.grpc.QueryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qsystem.exceljava.grpc.QueryResponse other) {
      if (other == com.qsystem.exceljava.grpc.QueryResponse.getDefaultInstance()) return this;
      if (!other.getUnderlyingModelJson().isEmpty()) {
        underlyingModelJson_ = other.underlyingModelJson_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              underlyingModelJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object underlyingModelJson_ = "";
    /**
     * <pre>
     * 底层模型JSON数据
     * </pre>
     *
     * <code>string underlying_model_json = 1;</code>
     * @return The underlyingModelJson.
     */
    public java.lang.String getUnderlyingModelJson() {
      java.lang.Object ref = underlyingModelJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        underlyingModelJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 底层模型JSON数据
     * </pre>
     *
     * <code>string underlying_model_json = 1;</code>
     * @return The bytes for underlyingModelJson.
     */
    public com.google.protobuf.ByteString
        getUnderlyingModelJsonBytes() {
      java.lang.Object ref = underlyingModelJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        underlyingModelJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 底层模型JSON数据
     * </pre>
     *
     * <code>string underlying_model_json = 1;</code>
     * @param value The underlyingModelJson to set.
     * @return This builder for chaining.
     */
    public Builder setUnderlyingModelJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      underlyingModelJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 底层模型JSON数据
     * </pre>
     *
     * <code>string underlying_model_json = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnderlyingModelJson() {
      underlyingModelJson_ = getDefaultInstance().getUnderlyingModelJson();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 底层模型JSON数据
     * </pre>
     *
     * <code>string underlying_model_json = 1;</code>
     * @param value The bytes for underlyingModelJson to set.
     * @return This builder for chaining.
     */
    public Builder setUnderlyingModelJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      underlyingModelJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.qsystem.exceljava.QueryResponse)
  }

  // @@protoc_insertion_point(class_scope:com.qsystem.exceljava.QueryResponse)
  private static final com.qsystem.exceljava.grpc.QueryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qsystem.exceljava.grpc.QueryResponse();
  }

  public static com.qsystem.exceljava.grpc.QueryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryResponse>
      PARSER = new com.google.protobuf.AbstractParser<QueryResponse>() {
    @java.lang.Override
    public QueryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QueryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qsystem.exceljava.grpc.QueryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

