// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

public interface QueryDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.qsystem.exceljava.QueryDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 认证token
   * </pre>
   *
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   * 认证token
   * </pre>
   *
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   * 标签名称
   * </pre>
   *
   * <code>string tag = 2;</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <pre>
   * 标签名称
   * </pre>
   *
   * <code>string tag = 2;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
