// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: excel_service.proto
// Protobuf Java Version: 4.29.3

package com.qsystem.exceljava.grpc;

public interface QueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.qsystem.exceljava.QueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 认证token
   * </pre>
   *
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   * 认证token
   * </pre>
   *
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   * 查询关键词
   * </pre>
   *
   * <code>string words = 2;</code>
   * @return The words.
   */
  java.lang.String getWords();
  /**
   * <pre>
   * 查询关键词
   * </pre>
   *
   * <code>string words = 2;</code>
   * @return The bytes for words.
   */
  com.google.protobuf.ByteString
      getWordsBytes();
}
